title: Disco 2000
author: Debra Ramirez
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing back songs that gave humanity countless hours of dance
  and memories while keeping it modern through nu-disco and disco
  revival. Boogie with us!
theme: minima
# social links
twitter_username: n_zaret # DO NOT include the @ character, or else the build will fail!
github_username:  nazaretnazaret # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
